---
params:
    batch_size: 50
    epoch: 5
    lr: 0.0001
    decay: 1
    decay_step: 10

save:
    metapath: "/home/chengyihua/work/PureGaze/Camera-ready/exp/Res50-PureGaze/"
    folder: eth
    name: eth
    step: 1

data:
    image: "/home/chengyihua/dataset/FaceBased/ETH-Gaze/Image/train/"
    label: "/home/chengyihua/dataset/FaceBased/ETH-Gaze/Label/train.label"
    header: True
    name: eth
    isFolder: False

pretrain: False
device: 0
reader: reader_adap
map: "/home/chengyihua/work/PureGaze/Camera-ready/Masker/eth-masker.jpg"
